pipeline {
    agent {
  label 'aws-deploy'
}

    stages {
        stage('Hello1') {
            steps {
                sh '''
                ls
                '''
            }
        }


        stage('Hello2') {
            steps {
                sh '''
                ls
                pwd
                ''' 
            }

        }


        stage('Hello3') {
            steps {
                sh '''
                ls
                pwd
                '''
            }
        }
        
    }
}