pipeline {
    agent {
  label 'aws-deploy'
}

    stages {
        stage('test auth') {
          agent {
            docker {
              image 'golang:alpine'
            }
           }    
            steps {
                sh '''
                ls
                pwd
                '''
            }
        }


        stage('Hello2') {
            steps {
                sh '''
                ls
                pwd
                uname
                ''' 
            }

        }


        stage('Hello3') {
            steps {
                sh '''
                ls
                pwd
                '''
            }
        }
        
    }
}